# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "rtsx_pci_sdmmc"
    "sd_mod"
    "usb_storage"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/6c870b03-4293-4810-8698-08cab6b01a77";
  #   fsType = "ext4";
  # };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d96b684c-4171-487d-b60f-642d25f03a3e";
    fsType = "ext4";
  };

  # boot.initrd.luks.devices."luks-caf63e81-a30e-4fc8-b13b-e3de8406027a".device = "/dev/disk/by-uuid/caf63e81-a30e-4fc8-b13b-e3de8406027a";

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/E367-01DB";
  #   fsType = "vfat";
  # };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7AD5-A5A7";
    fsType = "vfat";
  };

  # {device = "/dev/disk/by-uuid/73b223b8-714e-4566-afd5-d8f5e5d89e26";}
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
