keys:
  - &l380_age age1jhdxvuhz4552waas5plqfxv8r6reasluyu5y2tuv7qvuve8t3uvsu3jwp4
  - &l390_age age1pal8c0gk24dvmwsdxau4e8rmt2q8jjjypxm4seftjffcu3ffjdwqg664gh
  - &x220_age age1wepxydgqnud4keawpf3ge3ylck8cjeewu4h6y34jtkg5urz5k3pq9dasm9
creation_rules:
  - path_regex: secrets\.sops\.yaml$|aws\/.*\.sops\.yaml|gcp\/.*\.sops\.yaml$
    key_groups:
    - age:
      - *l380_age
      - *l390_age
      - *x220_age
